# Generated by Django 4.1.3 on 2022-12-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reksadana',
            new_name='TReksadana',
        ),
    ]
