# Generated by Django 4.1.3 on 2022-12-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana', '0002_rename_reksadana_treksadana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TReksadana',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
