# Generated by Django 4.1.3 on 2022-12-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana', '0005_twatchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TWatchlist',
        ),
    ]
