# Generated by Django 4.1.3 on 2022-12-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana', '0007_twatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twatchlist',
            name='id_reksadana',
        ),
    ]
