# Generated by Django 4.1.3 on 2022-12-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana', '0008_remove_twatchlist_id_reksadana'),
    ]

    operations = [
        migrations.AddField(
            model_name='twatchlist',
            name='id_reksadana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reksadana.treksadana'),
        ),
    ]
