# Generated by Django 4.1.3 on 2022-12-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana', '0009_twatchlist_id_reksadana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twatchlist',
            old_name='id_reksadana',
            new_name='name_reksadana',
        ),
    ]
