# Generated by Django 4.1.3 on 2022-12-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reksadana', '0010_rename_id_reksadana_twatchlist_name_reksadana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TWatchlist',
        ),
    ]
