# Generated by Django 4.1.3 on 2022-12-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tberita',
            name='author',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='publishedAt',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='urlToImage',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
