# Generated by Django 4.1.3 on 2022-12-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_tberita_author_alter_tberita_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tberita',
            name='author',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='publishedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='urlToImage',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
