# Generated by Django 4.1.3 on 2022-12-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_alter_tberita_author_alter_tberita_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_berita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='berita.tberita')),
            ],
            options={
                'verbose_name_plural': 'Type',
            },
        ),
    ]
