# Generated by Django 4.1.3 on 2022-12-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_typeberita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeberita',
            name='id_berita',
        ),
        migrations.AddField(
            model_name='tberita',
            name='tipe_berita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='berita.typeberita'),
        ),
    ]
