# Generated by Django 4.1.3 on 2022-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_remove_typeberita_id_berita_tberita_tipe_berita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tberita',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tberita',
            name='tipe_berita',
        ),
        migrations.AddField(
            model_name='tberita',
            name='tags',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tberita',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='TypeBerita',
        ),
    ]
