# Generated by Django 4.1.3 on 2022-12-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jenis',
            },
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Penulis',
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('jenis_buku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buku.jenis')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.penulis')),
            ],
            options={
                'verbose_name_plural': 'Buku',
            },
        ),
    ]
