# Generated by Django 4.1.3 on 2022-12-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='jenis_buku',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buku',
            name='penulis',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Jenis',
        ),
        migrations.DeleteModel(
            name='Penulis',
        ),
    ]
