# Generated by Django 4.1.3 on 2022-12-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taccount',
            old_name='group',
            new_name='list_group',
        ),
        migrations.RenameField(
            model_name='taccount',
            old_name='user',
            new_name='list_user',
        ),
    ]
